Foodezz/Foodezz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('',include('Users.urls')),
    path('admin/', admin.site.urls),
    path('Hotel/',include('Hotel.urls')),
    path('payments/', include('payments.urls')),
    path('gpstrack/',include('gpstrack.urls')),
    path('Paypal/', include('Paypal.urls')),
]

Foodezz/Users/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    ## Path for registrations of users
    path('Register/',views.Register,name='Users-Register'),
    path('',views.Home,name='Users-Home'),

    ## Paths for Email verification
    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activateAccout, name='Users-Activate'),

    ### Paths for the password reset
    path('Password-Reset/', auth_views.PasswordResetView.as_view(template_name='Users/Password-Reset.html'),
         name='password_reset'),
    path('Password-Reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='Users/Password-Reset-Done.html'),
         name='password_reset_done'),
    path('Password-Reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='Users/Password-Reset-Confirm.html'),
         name='password_reset_confirm'),
    path('Password-Reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='Users/Password-Reset-Complete.html'),
         name='password_reset_complete'),

    ## Path for editing profile
    path('Profile/',views.Profile,name='Users-Profile'),
    path('ChangePassword/',views.ChangePassword,name='Users-ChangePassword'),

    ## Path for Login and Logout
    path('Login/', views.Login, name='Users-Login'),
    path('Logout/', auth_views.LogoutView.as_view(template_name='Users/Logout.html'), name='Users-Logout'),

    # Path for Resturent login
    path('Rest_Login/',views.RestLogin,name='Rest-Login'),

    ## Path for Login through google api
    path('auth/',include('social_django.urls',namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Foodezz/blog/urls.py
from django.urls import path
from blog import views

app_name = "blog"

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:id>/post_edit/',views.post_edit, name='post_edit'),
    path('<int:id>/<slug:slug>/', views.post_detail, name='post_detail'),
    path('post_create/', views.post_create, name='post_create'),
    path('post_delete/<int:id>/',views.post_delete, name='post_delete'),
    path('like/', views.like_post, name='like_post'),
]

Foodezz/payments/urls.py
from django.urls import path

from . import views

app_name = "payments"

urlpatterns=[
    path('search',views.search,name='search'),
    path('pay/<rest>',views.pay,name='pay'),
    path('restupdate',views.restupdate,name='restupdate'),
    path('newitem',views.newitem,name='newitem'),
    path('mycart',views.mycart,name='mycart'),
    path('makecart',views.makecart,name='makecart'),
    path('restorders',views.restorder,name='restorder'),
    path('orderconfirm/<state>/<orderid>',views.orderconfirm,name='orderconfirm'),
    path('locaterestaurants/<location>', views.locaterestaurants, name='locaterestaurants'),
    path('showrestaurant/<restaurant>', views.showrestaurant, name='showrestaurant'),
    path('makeorderconfirm', views.makeorderconfirm, name='makeorderconfirm'),
    path('makeprev', views.makeprev, name='makeprev'),
    path('feedback', views.feedback, name='feedback'),
    path('feedbackthanks', views.feedbackthanks, name='feedbackthanks'),
    path('hotel/apiview/',views.HotelAPIView.as_view()),
    path('menu/apiview/',views.MenuAPIView.as_view()),
    path('customer/apiview/',views.CustomerOrdersAPIView.as_view()),
]

Foodezz/Users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

class User_Profile(models.Model):
    User = models.OneToOneField(User,on_delete=models.CASCADE)
    phone = models.DecimalField(max_digits=10,decimal_places=0)
    address = models.CharField(max_length=300)
    street = models.CharField(max_length=30,null=True)
    city = models.CharField(max_length=30)
    pincode = models.DecimalField(max_digits=6,decimal_places=0)
    image = models.ImageField(default='default.png',upload_to='profile_pics')
    rest = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.User.username} Profile'

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        super().save()

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            desired_size = (300 ,300)
            img.thumbnail(desired_size)
            img.save(self.image.path)

Foodezz/Users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from . import models as UserModels

class UserForm(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username','first_name','last_name','password1','password2','email',)

class User_Details(forms.ModelForm):

    address = forms.CharField(widget=forms.Textarea)
    pincode = forms.DecimalField(widget=forms.TextInput,max_digits=6)
    phone = forms.DecimalField(widget=forms.TextInput,max_digits=10)

    class Meta:
        model = UserModels.User_Profile
        fields = ('phone','address','street','city','pincode',)

class C_Login(forms.Form):
    Username = forms.CharField(max_length=30)
    Password = forms.CharField(widget=forms.PasswordInput)

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput)
    class Meta:
        model = User
        fields = ('username','first_name','last_name','email')

class ProfileUpdateForm(forms.ModelForm):
    image = forms.ImageField(required=False)
    class Meta:
        model = UserModels.User_Profile
        fields = ('phone','address','street','city','pincode','image')

class ChangePasswordform(forms.Form):
    Current_password = forms.CharField(widget=forms.PasswordInput,required=True)
    new_Password = forms.CharField(widget=forms.PasswordInput,required=True)
    Re_Password = forms.CharField(widget=forms.PasswordInput,required=True)

Foodezz/Users/views.py
from django.contrib.auth import authenticate, login
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from .tokens import account_activation_token
from Users.forms import C_Login
from . import forms
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.mail import EmailMessage, send_mail
from Foodezz.settings import EMAIL_HOST_USER
from . import decorators

def Register(request):
    if request.user.is_authenticated:
        messages.info(request, f'You are already logged in!, Log out to login from different account')
        return redirect('Users-Home')
    if(request.method == 'POST'):
        User_Form1 = forms.UserForm(request.POST)
        User_Details1 = forms.User_Details(request.POST,request.FILES)
        if User_Form1.is_valid() and User_Details1.is_valid():
            # print(User_Details1.cleaned_data.get('image'))
            if User.objects.filter(email = User_Form1.cleaned_data.get('email')).exists():
                messages.error(request, f'Email already exists go to login page to login')
                return render(request, 'Users/Register.html',
                              {'User_Form1': User_Form1, 'User_Details1': User_Details1})

            if len(str(User_Details1.cleaned_data.get('phone'))) is not 10:             ## For phone number to have 10 digits
                messages.error(request, f'Phone number should be of ten digits')
                return render(request, 'Users/Register.html', {'User_Form1': User_Form1, 'User_Details1':User_Details1})

            if len(str(User_Details1.cleaned_data.get('pincode'))) is not 6:            ## For pincode to have 6 digits
                messages.error(request,f'Enter valid pincode details')
                return render(request, 'Users/Register.html', {'User_Form1': User_Form1, 'User_Details1':User_Details1})

            username = User_Form1.cleaned_data.get('username')
            newuser_basic = User_Form1.save(commit=False)
            newuser_basic.is_active = False
            newuser_basic.save()
            newuser = User_Details1.save(commit=False)
            newuser.User = newuser_basic
            newuser.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your Food3zz account.'
            message = render_to_string('Users/acc_active_email.html', {
                'user': newuser_basic,
                'domain': current_site.domain,
                # 'uid': urlsafe_base64_encode(force_bytes(newuser_basic.pk)),
                'uid': newuser_basic.pk,
                'token': account_activation_token.make_token(newuser_basic),
            })
            to_email = User_Form1.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            messages.success(request, f'confirm your mail to complete registration for {username}!')
            return redirect('Users-Login')
    else:
        User_Form1 = forms.UserForm()
        User_Details1 = forms.User_Details()
    return render(request, 'Users/Register.html', {'User_Form1': User_Form1, 'User_Details1':User_Details1})


def activateAccout(request, uidb64, token):
    try:
        # print(uidb64 + "   " + token)
        # uid = force_text(urlsafe_base64_decode(uidb64))
        # print(int(uidb64))
        uid = uidb64
        user = User.objects.get(pk=int(uid))

    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None:
        if account_activation_token.check_token(user, token):
            user.is_active = True
            user.save()
            messages.success(request, f'Account created successfully!')
            return redirect('Users-Home')
        else:
            return HttpResponse('Didnt match the token')
    else:
        return HttpResponse('Activation link is invalid!')


def Home(request):
    if request.user.is_authenticated:
        if not hasattr(request.user, 'user_profile'):
            return redirect('Users-AddDetails')
    return render(request,'Users/Home.html',)

def Login(request):
    if request.user.is_authenticated:
        messages.info(request,f'You are already logged in!')
        return redirect('Users-Home')
    if request.method == 'POST':
        name = request.POST.get('Username')
        pword = request.POST.get('Password')

        user = authenticate(username=name,password=pword)

        if user and user.user_profile.rest == False:
            if user.is_active:
                login(request,user)
                return redirect('Users-Home')
            else:
                messages.error(request,f'Account not in active state')
                return redirect('User-Login')
        else:
            messages.error(request, f'Invalid login details')
            Log_form = C_Login(request.POST)
    else:
        Log_form = C_Login()
    return render(request,'Users/Login.html',{'Login_form':Log_form})

@login_required
def Profile(request,username):
    if not hasattr(request.user, 'user_profile'):
        return redirect('Users-AddDetails')
    if request.method == 'POST':
        u_form = forms.UserUpdateForm(request.POST, instance=request.user)
        p_form = forms.ProfileUpdateForm(request.POST, files=request.FILES, instance=request.user.user_profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated successfully!')
            return redirect('Users-Profile',request.user.username)

    else:
        u_form = forms.UserUpdateForm(instance= request.user)
        p_form = forms.ProfileUpdateForm(instance= request.user.user_profile)

    return render(request,'Users/Profile.html',{'u_form':u_form,'p_form':p_form,})


def RestLogin(request):
    if request.user.is_authenticated:
        messages.info(request, f'You are already logged in!, Log out to login from different account')
        return redirect('Users-Home')
    if request.method == "POST":
        name = request.POST.get('Username')
        pword = request.POST.get('Password')

        user = authenticate(username=name, password=pword)
        if user and user.user_profile.rest == True:
            if user.is_active:
                login(request, user)
                return redirect('Hotel-ItemView')
            else:
                messages.error(request, f'Account not in active state')
                return redirect('Users-Login')
        else:
            messages.error(request, f'Invalid login details')
            Rest_Login_Form = C_Login(request.POST)
    else:
        Rest_Login_Form = C_Login()
    return render(request,'Users/Rest-Login.html',{'Login_form':Rest_Login_Form})

@decorators.Details_Required
def ChangePassword(request):
    if request.method == 'POST':
        ChangePassForm = forms.ChangePasswordform(request.POST)
                                                                            # validate the password given
        pword = request.POST.get('Current_password')
        # print('got password')
        uname = request.user.username
        # print('got username')
        user = authenticate(username=uname,password=pword)

        if user == request.user:
                                                                                            # Check same password in both fields
            new_Password = request.POST.get('new_Password')
            # print(new_Password)
            new_Password1 = request.POST.get('Re_Password')
            # print(new_Password1)

            if new_Password == new_Password1:

                if len(new_Password) <= 4:                                              # Check for password meets the minimum security
                    messages.error(request, f'Password should more then 4 characters')
                    return redirect('Users-ChangePassword')

                else:
                    user.set_password(new_Password)                                                # Change the password for the user and logout.
                    user.save()

                                                                                                    # Mail the user about the change in password
                    mail_subject = "Hi, "+ user.username + " alert for Food3zz account"
                    message = "Your Food3zz account password has been changed. /nIf you didn't change the password you can always go to our home page and reset your password."
                    mail_address = user.email
                    # print(user.email)
                    send_mail(mail_subject, message, 'EMAIL_HOST_USER',[mail_address], fail_silently=True)

                    messages.success(request, f"Password successfully changed, now login to your account")
                    return redirect('Users-Login')

            else:
                messages.error(request, f"Passwords didn't match")

        else:
            messages.error(request,f'User can not be found')

    else:
        ChangePassForm = forms.ChangePasswordform()
    return render(request,'Users/ChangePassword.html',{'ChangePassForm':ChangePassForm})

@login_required
def AddDetails(request):
    if not hasattr(request.user, 'user_profile'):
        if request.method == 'POST':
            p_form = forms.ProfileUpdateForm(request.POST,request.FILES)
            if p_form.is_valid():
                newUser = p_form.save(commit=False)
                newUser.User = request.user
                newUser.save()

Foodezz/Users/templates/Users/Base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="{% static 'Materialize/CSS/materialize.css' %}">
{#        <link rel="stylesheet" href="{% static 'Login/CSS/header.css' %}">#}
        <link rel="stylesheet" href="{% static 'Login/CSS/Googleicon.css' %}">
        <link rel="stylesheet" href="{% static "Login/CSS/karthik_header.css" %}">

        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    {% block head %}{% endblock head %}
    </head>
    <body>
        <div class="page-overlay"></div>

{#            <ul>#}
{#                <li><a class="active" href='{% url 'Users-Home' %}'>Home</a></li>#}
{#                {% if user.is_authenticated %}#}
{#                    <li style="float:right"><a href={% url 'Users-Logout' %}>Logout</a></li>#}
{#                    <li style="float:right"><a href={% url 'Users-Profile' %}>Profile</a></li>#}
{#                {% else %}#}
{#                    <li style="float:right"><a href={% url 'Users-Login' %}>Login</a></li>#}
{#                    <li style="float:right"><a href={% url 'Rest-Login' %}>Hotel Login</a></li>#}
{#                    <li style="float:right"><a href={% url 'Users-Register' %}>Custumer Register</a></li>#}
{#                {% endif %}#}
{#            </ul>#}

            <ul class="nav">
                <li id="settings">
                    <a href="{% url 'Users-Home' %}"><img src="{% static 'Login/Media/123.png' %}" height=100px width=200px/></a>
                </li>
                <li>
                    <a href="#">About Us</a>
                </li>
                <li id="search">
                    <form autocomplete="off" action="{% url "payments:search" %}" method="post">
                        {% csrf_token %}
{#                        <div class="autocomplete" style="width:300px;">#}
                        <input id="myInput" type="text" name="myCountry" placeholder="Search">
{#                        </div>#}
                        <input type="submit" name="search_button" id="search_button">
                    </form>
                </li>
                {% if user.is_authenticated %}
                    <div class="right">
                        <li id="options">
                            <a href="#">Hi ,{{ user.username }}</a>
                            <ul class="subnav">
                                <li><a href="{% url "payments:makecart" %}">My Cart</a></li>
                                <li><a href="{% url "payments:makeorderconfirm" %}">Order confirmation</a></li>
                                <li><a href="{% url "payments:makeprev" %}">Previous bookings</a></li>
                                <li><a href="{% url 'Users-Profile' user.username %}">Profile</a></li>
                                <li><a href="{% url 'Users-ChangePassword' %}">Change password</a></li>
                                <li><a href="{% url 'Users-Logout' %}">Logout</a></li>
                            </ul>
                        </li>
                    </div>
                {% else %}
                    <div class="right">
                        <li>
                            <a href="{% url 'Users-Login' %}">
                                Login
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'Users-Register' %}">
                                Register
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'Rest-Login' %}">
                                Hotel Login
                            </a>
                        </li>
                    </div>
                {% endif %}
            </ul>



            <div style="padding:70px;margin-top:30px;">
                <div class='container'>
                    <div class='row'>
                        <div class='col s4 offset-s4'>
                            {% if messages %}
                                {% for message in messages %}
                                    {% if message.tags == 'info' %}
                                        <div class='card blue lighten-1'>
                                            <div class='center'>
                                                {{ message }}
                                            </div>
                                        </div>
                                    {% elif message.tags == 'success' %}
                                        <div class='card green lighten-1'>
                                            <div class='center'>
                                                {{ message }}
                                            </div>
                                        </div>
                                    {% elif message.tags == 'error' %}
                                        <div class='card red lighten-1'>
                                            <div class='center'>
                                                {{ message }}
                                            </div>
                                        </div>
                                    {% else %}
                                        <div class='card gray lighten-1'>
                                            <div class='center'>
                                                {{ message }}
                                            </div>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>

            {% block body %}

            {% endblock body %}



          <footer class="footer-distributed">
              <div class="footer-left">
                    <h3>F00d3zz</h3>
                    <p class="footer-links">
                        <a href="{% url 'Users-Home' %}">Home</a>
                        ·
                        <a href="{% url "blog:post_list" %}">Blog</a>
                        ·
                        <a href="#">About</a>
                        ·
                        <a href="#">Contact</a>
                    </p>

              <p class="footer-company-name">Food3zz &copy; 2018</p>

                  <div class="footer-icons">

                  <a href="#"><i class="fa fa-facebook"></i></a>
                  <a href="#"><i class="fa fa-twitter"></i></a>
                  <a href="#"><i class="fa fa-github"></i></a>

                  </div>

              </div>

          </footer>



        <script type="text/javascript"  src="{% static 'Materialize/JS/materialize.js' %}"></script>
        <script>
function autocomplete(inp, arr) {
  /*the autocomplete function takes two arguments,
  the text field element and an array of possible autocompleted values:*/
  var currentFocus;
  /*execute a function when someone writes in the text field:*/
  inp.addEventListener("input", function(e) {
      var a, b, i, val = this.value;
      /*close any already open lists of autocompleted values*/
      closeAllLists();
      if (!val) { return false;}
      currentFocus = -1;
      /*create a DIV element that will contain the items (values):*/
      a = document.createElement("DIV");
      a.setAttribute("id", this.id + "autocomplete-list");
      a.setAttribute("class", "autocomplete-items");
      /*append the DIV element as a child of the autocomplete container:*/
      this.parentNode.appendChild(a);
      /*for each item in the array...*/
      for (i = 0; i < arr.length; i++) {
        /*check if the item starts with the same letters as the text field value:*/
        if (arr[i].substr(0, val.length).toUpperCase() == val.toUpperCase()) {
          /*create a DIV element for each matching element:*/
          b = document.createElement("DIV");
          /*make the matching letters bold:*/
          b.innerHTML = "<strong>" + arr[i].substr(0, val.length) + "</strong>";
          b.innerHTML += arr[i].substr(val.length);
          /*insert a input field that will hold the current array item's value:*/
          b.innerHTML += "<input type='hidden' value='" + arr[i] + "'>";
          /*execute a function when someone clicks on the item value (DIV element):*/
          b.addEventListener("click", function(e) {
              /*insert the value for the autocomplete text field:*/
              inp.value = this.getElementsByTagName("input")[0].value;
              /*close the list of autocompleted values,
              (or any other open lists of autocompleted values:*/
              closeAllLists();
          });
          a.appendChild(b);
        }
      }
  });
  /*execute a function presses a key on the keyboard:*/
  inp.addEventListener("keydown", function(e) {
      var x = document.getElementById(this.id + "autocomplete-list");
      if (x) x = x.getElementsByTagName("div");
      if (e.keyCode == 40) {
        /*If the arrow DOWN key is pressed,
        increase the currentFocus variable:*/
        currentFocus++;
        /*and and make the current item more visible:*/
        addActive(x);
      } else if (e.keyCode == 38) { //up
        /*If the arrow UP key is pressed,
        decrease the currentFocus variable:*/
        currentFocus--;
        /*and and make the current item more visible:*/
        addActive(x);
      } else if (e.keyCode == 13) {
        /*If the ENTER key is pressed, prevent the form from being submitted,*/
        e.preventDefault();
        if (currentFocus > -1) {
          /*and simulate a click on the "active" item:*/
          if (x) x[currentFocus].click();
        }
      }
  });
  function addActive(x) {
    /*a function to classify an item as "active":*/
    if (!x) return false;
    /*start by removing the "active" class on all items:*/
    removeActive(x);
    if (currentFocus >= x.length) currentFocus = 0;
    if (currentFocus < 0) currentFocus = (x.length - 1);
    /*add class "autocomplete-active":*/
    x[currentFocus].classList.add("autocomplete-active");
  }
  function removeActive(x) {
    /*a function to remove the "active" class from all autocomplete items:*/
    for (var i = 0; i < x.length; i++) {
      x[i].classList.remove("autocomplete-active");
    }
  }
  function closeAllLists(elmnt) {
    /*close all autocomplete lists in the document,
    except the one passed as an argument:*/
    var x = document.getElementsByClassName("autocomplete-items");
    for (var i = 0; i < x.length; i++) {
      if (elmnt != x[i] && elmnt != inp) {
        x[i].parentNode.removeChild(x[i]);
      }
    }
  }
  /*execute a function when someone clicks in the document:*/
  document.addEventListener("click", function (e) {
      closeAllLists(e.target);
  });
}

/*An array containing all the country names in the world:*/
var countries = ["tada","swathi","kitchen","sunny"];

/*initiate the autocomplete function on the "myInput" element, and pass along the countries array as possible autocomplete values:*/
autocomplete(document.getElementById("myInput"), countries);
</script>



    </body>
</html>

Foodezz/Users/templates/Users/GoogleLogin.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="google-signin-scope" content="profile email">
    <meta name="google-signin-client_id" content="420290905831-eo2q672ulpdgfs30pilbmmrmq8jqf147.apps.googleusercontent.com">
    <script src="https://apis.google.com/js/platform.js" async defer></script>
  </head>
  <body>
    <div class="g-signin2" data-onsuccess="onSignIn" data-theme="dark"></div>
    <script>
      function onSignIn(googleUser) {
        // Useful data for your client-side scripts:
        var profile = googleUser.getBasicProfile();
        console.log("ID: " + profile.getId()); // Don't send this directly to your server!
        console.log('Full Name: ' + profile.getName());
        console.log('Given Name: ' + profile.getGivenName());
        console.log('Family Name: ' + profile.getFamilyName());
        console.log("Image URL: " + profile.getImageUrl());
        console.log("Email: " + profile.getEmail());

        // The ID token you need to pass to your backend:
        var id_token = googleUser.getAuthResponse().id_token;
        console.log("ID Token: " + id_token);
      };
    </script>
  </body>
</html>

Foodezz/Users/templates/Users/Logout.html
{% extends 'Users/Base.html' %}

{% block head %}
    <title>
        Logout-Page
    </title>
{% endblock head %}

{% block body %}
    <h1>You have been successfully logged out.</h1>
    <br>
    To login again click
    <a href="{% url 'Users-Login' %}">here</a>
{% endblock body %}

Foodezz/Users/templates/Users/Password-Reset-Complete.html
{% extends 'Users/Base.html' %}
{% load crispy_forms_tags %}

{% block head %}
    <title>
        Password-Reset-Complete - Page
    </title>
    <meta http-equiv="Refresh" content="5;{% url 'Users-Login' %}">
{% endblock head %}

{% block body %}
    <div class="alert alert-info">
        Your password has been set. You should be redirected to login page in 5 seconds. If not then click on the below link to login.
    </div>
    <a href="{% url 'Users-Login' %}">Sign In here</a>
{% endblock body %}

Foodezz/Users/templates/Users/Password-Reset-Confirm.html
{% extends 'Users/Base.html' %}
{% load crispy_forms_tags %}

{% block head %}
    <title>
        Password-Reset-Confirm - Page
    </title>
{% endblock head %}

{% block body %}
    <div class="container">
        <div class="row">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                <legend class="border-bottom mb-4" style="text-align: center">
                    Reset Password
                </legend>
                <div class="col-md-12">
                    {{  form|crispy }}
                </div>
                </fieldset>
                <div class="col-md-12">
                    <button type="submit" class="btn btn-outline-info register_btn">Reset Password</button>
                </div>
            </form>
        </div>
    </div>
{% endblock body %}

Foodezz/Users/templates/Users/Password-Rest-Done.html
{% extends 'Users/Base.html' %}
{% load crispy_forms_tags %}

{% block head %}
    <title>
        Password-Reset-Done - Page
    </title>
{% endblock head %}

{% block body %}
    <div class="alert alert-info">
        An email has been sent with instructions to reset your password
    </div>
{% endblock body %}