Foodezz/Foodezz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('',include('Users.urls')),
    path('admin/', admin.site.urls),
    path('Hotel/',include('Hotel.urls')),
    path('payments/', include('payments.urls')),
    path('gpstrack/',include('gpstrack.urls')),
    path('Paypal/', include('Paypal.urls')),
]

Foodezz/blog/urls.py
from django.urls import path
from blog import views

app_name = "blog"

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:id>/post_edit/',views.post_edit, name='post_edit'),
    path('<int:id>/<slug:slug>/', views.post_detail, name='post_detail'),
    path('post_create/', views.post_create, name='post_create'),
    path('post_delete/<int:id>/',views.post_delete, name='post_delete'),
    path('like/', views.like_post, name='like_post'),
]

Foodezz/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.text import slugify


class PublishedManager(models.Manager):
	def get_queryset(self):
		return super(PublishedManager, self).get_queryset().filter(status="published")

class Post(models.Model):
	objects = models.Manager()
	published = PublishedManager()
	STATUS_CHOICES = (
		('draft', 'Draft'),
		('published', 'Published'),
	)
	title = models.CharField(max_length=100)
	slug = models.SlugField(max_length=120)
	author = models.ForeignKey(User, related_name='blog_posts', on_delete=models.CASCADE)
	body = models.TextField()
	likes = models.ManyToManyField(User, related_name='likes', blank=True )
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
	restrict_comment = models.BooleanField(default=False)
	

	class Meta:
		ordering = ['-id']

	def __str__(self):
		return self.title 	

	def total_likes(self):
		return self.likes.count()

	def get_absolute_url(self):
		return reverse("blog:post_detail", args=[self.id,self.slug])

@receiver(pre_save, sender=Post)
def pre_save_slug(sender, **kwargs):
	slug = slugify(kwargs['instance'].title)
	kwargs['instance'].slug = slug




class Images(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	image = models.ImageField(upload_to='images/', blank=True, null=True)

	def __str__(self):
		return self.post.title + " Image"



class Comment(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	reply = models.ForeignKey('Comment', null=True, related_name="replies", on_delete=models.CASCADE)
	content = models.TextField(max_length=160)
	timestamp = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return '{}-{}'.format(self.post.title, str(self.user.username))

Foodezz/blog/forms.py
from django import forms
from .models import Post, Comment

class PostCreateForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = (
			'title',
			'body',
			'status',
			'restrict_comment',
		)

class PostEditForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = (
			'title',
			'body',
			'status',
			'restrict_comment',
		)

class UserLoginForm(forms.Form):
	username = forms.CharField(label='')
	password = forms.CharField(label='', widget=forms.PasswordInput)

class CommentForm(forms.ModelForm):
	content = forms.CharField(
		label="",
		widget=forms.Textarea(
			attrs={
				'class': 'form-control',
				'placeholder': 'Text goes Here!!!!',
				'rows':'4', 'cols':'50'
			}
		)
	)
	class Meta:
		model = Comment
		fields = ('content',)

Foodezz/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse,Http404, HttpResponseRedirect, JsonResponse
from datetime import datetime
from .models import Post, Images, Comment
from django.urls import reverse
from .forms import *
from django.contrib.auth import authenticate, login, logout
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template.loader import render_to_string
from django.forms import modelformset_factory
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required

def post_list(request):
	post_list = Post.published.all()
	query = request.GET.get('q')
	if(query):
		post_list = Post.published.filter(
			Q(title__icontains=query)|
			Q(author__username=query)|
			Q(body__icontains=query)
		)
	paginator = Paginator(post_list, 5)
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)
	if page is None:
		start_index = 0
		end_index = 7
	else:
		(start_index, end_index) = proper_pagination(posts, index=4)
	page_range = list(paginator.page_range)[start_index:end_index]


	context = {
		'posts': posts,
		'page_range': page_range,
	}
	return render(request, 'blog/post_list.html',context)


def proper_pagination(posts, index): 
	start_index = 0
	end_index = 7
	if posts.number>index:
		start_index = posts.number - index
		end_index = start_index + end_index
	return (start_index, end_index)

def post_detail(request, id, slug):
    post = get_object_or_404(Post, id=id, slug=slug)
    comments = Comment.objects.filter(post=post, reply=None).order_by('-id')
    is_liked = False
    is_favourite = False
    if post.likes.filter(id=request.user.id).exists():
        is_liked = True


    if request.method == 'POST':
        comment_form = CommentForm(request.POST or None)
        if comment_form.is_valid():
            content = request.POST.get('content')
            reply_id = request.POST.get('comment_id')
            comment_qs = None
            if reply_id:
                comment_qs = Comment.objects.get(id=reply_id)
            comment = Comment.objects.create(post=post, user=request.user, content=content, reply=comment_qs)
            comment.save()
            # return HttpResponseRedirect(post.get_absolute_url())
    else:
        comment_form= CommentForm()

    context = {
        'post': post,
        'is_liked': is_liked,
        'is_favourite': is_favourite,
        'total_likes': post.total_likes(),
        'comments': comments,
        'comment_form': comment_form,
    }
    if request.is_ajax():
        html = render_to_string('blog/comments.html', context, request=request)
        return JsonResponse({'form': html})

    return render(request, 'blog/post_detail.html', context)


def like_post(request):
	post = get_object_or_404(Post, id=request.POST.get('post_id'))
	is_liked = False
	if post.likes.filter(id=request.user.id).exists():
		post.likes.remove(request.user)
		is_liked = False
	else:
		post.likes.add(request.user)	
		is_liked = True
	context = {
		'post': post,
		'is_liked': is_liked,
		'total_likes': post.total_likes()
	}
	if(request.is_ajax()):
		html = render_to_string('blog/like_section.html', context, request=request)
		return JsonResponse({'form':html})

@login_required
def post_create(request):
	ImageFormset = modelformset_factory(Images, fields=('image',))
	if(request.method == 'POST'):
		form = PostCreateForm(request.POST)
		formset = ImageFormset(request.POST or None, request.FILES or None)
		if(form.is_valid() and formset.is_valid()):
			post = form.save(commit=False)
			post.author = request.user
			post.save()

			for f in formset:
				try:
					photo = Images(post=post, image=f.cleaned_data.get('image'))
					photo.save()
				except Exception as e:
					break
			messages.success(request, "Post has been successfully created.")
			return redirect('blog:post_list')
				
	else:
		form = PostCreateForm()
		formset = ImageFormset(queryset = Images.objects.none())
	context = {
		'form': form,
		'formset': formset,
	}
	return render(request, 'blog/post_create.html', context)

def post_edit(request, id):
	post = get_object_or_404(Post, id=id)
	ImageFormset = modelformset_factory(Images, fields=('image',),max_num=1)
	if(post.author != request.user):
		raise Http404()
	if(request.method=="POST"):
		form = PostEditForm(request.POST or None, instance=post)
		formset = ImageFormset(request.POST or None, request.FILES or None)
		if(form.is_valid() and formset.is_valid()):
			form.save()
			print(formset.cleaned_data)
			data = Images.objects.filter(post=post)
			for index, f in enumerate(formset):
				if(f.cleaned_data):
					if(f.cleaned_data['id'] is None):
						photo = Images(post=post, image=f.cleaned_data.get('image'))
						photo.save()
					elif(f.cleaned_data['image'] is False):
						photo = Images.objects.get(id=request.POST.get('form-'+str(index)+'-id'))
						photo.delete()
					else:
						photo = Images(post=post, image=f.cleaned_data.get('image'))
						d = Images.objects.get(id=data[index].id)
						d.image = photo.image
						d.save()
			messages.success(request, "{} has been successfully updated".format(post.title))
			return HttpResponseRedirect(post.get_absolute_url())
	else:
		form = PostEditForm(instance=post)
		formset = ImageFormset(queryset=Images.objects.filter(post=post))
	context = {
		'form': form,
		'post': post,
		'formset': formset,
	}
	return render(request, 'blog/post_edit.html', context)

def post_delete(request, id):
	post = get_object_or_404(Post, id=id)
	user = User.objects.get(username=request.user)
	print("fuck")
	if(user != post.author):
		print("fuck")
		raise Http404()
	post.delete()
	messages.warning(request, "post has been successfully deleted!")
	return redirect('blog:post_list')

def user_login(request):
	if(request.method=='POST')	:
		form = UserLoginForm(request.POST)
		
		if(form.is_valid()):
			username = request.POST['username']
			password = request.POST['password']
			user = authenticate(username=username, password=password)
			if(user):
				if(user.is_active):
					login(request, user)
					return HttpResponseRedirect(reverse('post_list'))
				else:
					return HttpResponse("User is not Active")
			else:
				return HttpResponse("User is none")
	else:
		form = UserLoginForm()

	context = {
		'form': form,
	}
	return render(request, 'blog/login.html', context)

def user_logout(request):
	logout(request)
	return redirect('post_list')

Foodezz/blog/templates/blog/alerts.html
<div class="messages">
	{% if messages %}
		{% for message in messages %}
			<p class="alert alert-{{ message.tags }}">
				{{ message }}
			</p>
		{% endfor %}
	{% endif %}
</div>

Foodezz/blog/templates/blog/base.html
	<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>{% block title %}F00d33z{% endblock %}</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'blog/style.css' %}">
</head>
<body>
	{% include 'blog/navbar.html' %}
	<div class="container-fluid">
		{% block content %}
		{% endblock %}
	</div>


	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

	<script type="text/javascript">
		$(function(){
			setTimeout(function(){
				$('.alert'.slideUp(2000));
			}, 5000);
		});

		$('.reply-btn').click(function(){
			$(this).parent().parent().next('.replied-comments').fadeToggle()
		});
		$(document).ready(function(event){
			$(document).on('click', '#like', function(event){
				event.preventDefault();
				var pk = $(this).attr('value');
				$.ajax({
					type: 'POST',
					url: '{% url "blog:like_post" %}',
					data: {'post_id':pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
					dataType: 'json',
					success: function(response){
						$('#like-section').html(response['form'])
						console.log($('#like-section').html(response['form']));
					},
					error: function(rs,e){
						console.log(rs.responseText);
					},
				});
			});
		});


		$(document).on('submit', '.comment-form', function(event){
          event.preventDefault();
          console.log($(this).serialize());
          $.ajax({
            type: 'POST',
            url: $(this).attr('action'),
            data: $(this).serialize(),
            dataType: 'json',
            success: function(response) {
              $('.main-comment-section').html(response['form']);
              $('textarea').val('');
              $('.reply-btn').click(function() {
                $(this).parent().parent().next('.replied-comments').fadeToggle();
                $('textarea').val('');
              });
            },
            error: function(rs, e) {
              console.log(rs.responseText);
            },
          });
        });


		$(document).on('submit', '.reply-form', function(event){
          event.preventDefault();
          console.log($(this).serialize());
          $.ajax({
            type: 'POST',
            url: $(this).attr('action'),
            data: $(this).serialize(),
            dataType: 'json',
            success: function(response) {
              $('.main-comment-section').html(response['form']);
              $('textarea').val('');
              $('.reply-btn').click(function() {
                $(this).parent().parent().next('.replied-comments').fadeToggle();
                $('textarea').val('');
              });
            },
            error: function(rs, e) {
              console.log(rs.responseText);
            },
          });
        });
	</script>
</body>
</html>

Foodezz/blog/templates/blog/comments.html
<div class="container-fluid mt-2">
	<div class="form-group row">
		<form method="post" class="comment-form" action=".">
		{% csrf_token %}
		{{ comment_form.as_p }}
		{% if request.user.is_authenticated %}
			<input type="submit" value="Submit" class="btn btn-outline-success">
		{% else %}
			<input type="submit" value="Submit" class="btn btn-outline-success" disabled>
		{% endif %}
		</form>
	</div>
</div>
{{ comments.count }}
{% if comments.count > 1 %}
	comments
{% else %}
	comment
{% endif %}
<!--{{ comments.count }} Comment{{ comments|pluralize }}-->
{% for comment in comments %}
<blockquote class="blockquote">
  <p class="mb-0"><small>{{ comment.content }}</small></p>
  <footer class="blockquote-footer">
  	<small>
	  	By <cite title="Source Title">{{ comment.user|capfirst }}</cite>
  	</small>
  	<button type="button" name="button" class="reply-btn btn btn-outline-dark btn-sm ml-2">Reply</button>
  </footer>
</blockquote>
<div class="replied-comments container mt-2" style="display: none;">
	{% for reply in comment.replies.all %}
		<blockquote class="blockquote">
		  <p class="mb-0"><small>{{ reply.content }}</small></p>
		  <footer class="blockquote-footer"><small>By <cite title="Source Title">{{ reply.user|capfirst }}</cite></small>
		  </footer>
		</blockquote>
	{% endfor %}
<div class="form-group">
<form method="post" class="reply-form" action=".">
	{% csrf_token %}
	<input type="hidden" name="comment_id" value="{{ comment.id }}">
	{{ comment_form.as_p }}
	{% if request.user.is_authenticated %}
		<input type="submit" value="Submit" class="btn btn-outline-success">
	{% else %}
		<input type="submit" value="Submit" class="btn btn-outline-success" disabled>
	{% endif %}
</form>
</div>
</div>
{% endfor %}

Foodezz/blog/templates/blog/like_section.html
{{ total_likes }} Like{{ total_likes|pluralize}}

{% if request.user.is_authenticated %}
<form action="{% url 'blog:like_post' %}" method="post">
	{% csrf_token %}
	{% if is_liked %}
	<button id="like" type="submit" name='post_id' value='{{ post.id }}' class="btn btn-danger">DisLike</button>
	{% else %}
	<button id="like" type="submit" name='post_id' value='{{ post.id }}' class="btn btn-primary">Like</button>
	{% endif %}
</form>

{% endif %}

Foodezz/blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% block content %}
	<form method="post">
		{% csrf_token %}
		Username:
		{{ form.as_p }}
		<input type="submit" value="Login" class="btn btn-outline-success ">
	</form>
{% endblock %}

Foodezz/blog/templates/blog/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
 <div class="container">
 	 <a class="navbar-brand" href="{% url 'blog:post_list' %}">F00d33z Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
		<form class="form-inline my-2 my-lg-0" action="{% url 'blog:post_list' %}">
			<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
			<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
		</form>
    </ul>
    <ul class="navbar-nav">
		{% if request.user.is_authenticated %}
		<li class="nav-item dropdown">
        	<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        	<span>Hi {{ request.user|capfirst }}</span>
        	</a>
        	<div class="dropdown-menu">
        		<a class="dropdown-item" href="{% url 'blog:post_create' %}">Create A Post!</a>  
        		<a class="dropdown-item" href="{% url 'Users-Logout' %}">Logout</a>  
        	</div>
      </li>
      	{% else %}
		<li class="nav-item">
			<a href="{% url 'Users-Login' %}" class="nav-link">Login</a>
		</li>  
		{% endif %}	
    </ul>
  </div>
 </div>
</nav>

Foodezz/blog/templates/blog/post_create.html
{% extends 'blog/base.html' %}
{% block content %}
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		{{ formset.as_table}}
		<input type="submit" value="Create" class="btn btn-outlined-success">
	</form>
{% endblock %}

Foodezz/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block title %}{{ post.title }} | {{ block.super }}{% endblock %}
{% block content %}
{% include 'blog/alerts.html' %}

<h3>{{ post.title }}</h3>
<small>Post created by: {{ post.author }}</small>
<hr>
<p>{{ post.body }}</p>
<div class="row gallary">
	{% for p in post.images_set.all %}
		<div class="col-md-3">
			{% if p.image %}
			<img src="{{ p.image.url }}" alt="Image Not Found" class="img-thumbnail">
			{% endif %}
		</div>
	{% endfor %}
</div>
<div id="like-section">
	{% include 'blog/like_section.html' %}
</div>
{% if post.author == request.user %}
<div class="section-1" style="float: right;">
	<a href="{% url 'blog:post_edit' id=post.id %}">
		<button type="button" class="btn btn-outline-success">Edit</button>
	</a>
	
		<button type="button" id="delete" class="btn btn-danger" onclick="post_delete()">
			Delete
		</button>
	
</div>
<script type="text/javascript">
	function post_delete(){
		if(confirm("Are you sure you want to delete?")){
			location.href="{% url 'blog:post_delete' id=post.id %}"
		} else{

		}
	}
</script>
{% endif %}
<br><br>
<hr>
{% if not post.restrict_comment %}
	<div class="main-comment-section">
		{% include 'blog/comments.html' %}
	</div>
{% endif %}
{% endblock %}

Foodezz/blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}
{% block title %}
	{{ post.title }}|Edit
{% endblock %}

{% block content %}
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		{{ formset.management_form }}
		{% for f in formset %}
			{{ f.as_p }}
		{% endfor %}
		<input type="submit" value="Update" class="btn btn-success">
	</form>
{% endblock %}

Foodezz/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block title %}Welcome to {{ post.title }} | {{ block.super }}{% endblock %}

{% block content %}
{% if messages %}
{% include 'blog/alerts.html' %}
{% endif %}
<div class="container">
	{% if posts %}
	<div class="row">
	{% for p in posts %}
		<div class="col-9">
			<div class="img-thumbnail">
				<a href="{{ p.get_absolute_url }}">{{ p.title }}</a><small style="float: right">{{ p.created }}</small><br>
				Author: {{ p.author }}<br>
				{{ p.body }}
			</div>
			<br>	
		</div>
	{% empty %}
		<div class="container-fluid">
			<h3>No Posts Found having search query "{{ request.GET.q }}"</h3>
		</div>
	{% endfor %}
	
</div>
<ul class="pagination">
	{% if posts.has_previous %}
		<li class="page-item">
			<a class="page-link" href="?page={{ posts.previous_page_number }}">&laquo;</a>
		</li>
	{% endif %}
	{% for p in page_range %}
		{% if posts.number == p %}
			<li class="page-item active">
				<a href="?page={{ p }}" class="page-link">{{ p }}</a>
			</li>
		{% else %}
		<li class="page-item">
			<a href="?page={{ p }}" class="page-link">{{ p }}</a>
		</li>
		{% endif %}
	{% endfor %}
	{% if posts.has_next %}
		<li class="page-item">
			<a href="?page={{ posts.next_page_number }}" class="page-link">&raquo;</a>
		</li>
	{% endif %}
{% endif %}	
</ul>
</div>
{% endblock %}