Foodezz/Foodezz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('',include('Users.urls')),
    path('admin/', admin.site.urls),
    path('Hotel/',include('Hotel.urls')),
    path('payments/', include('payments.urls')),
    path('gpstrack/',include('gpstrack.urls')),
    path('Paypal/', include('Paypal.urls')),
]

Foodezz/blog/urls.py
from django.urls import path
from blog import views

app_name = "blog"

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:id>/post_edit/',views.post_edit, name='post_edit'),
    path('<int:id>/<slug:slug>/', views.post_detail, name='post_detail'),
    path('post_create/', views.post_create, name='post_create'),
    path('post_delete/<int:id>/',views.post_delete, name='post_delete'),
    path('like/', views.like_post, name='like_post'),
]

Foodezz/payments/urls.py
from django.urls import path

from . import views

app_name = "payments"

urlpatterns=[
    path('search',views.search,name='search'),
    path('pay/<rest>',views.pay,name='pay'),
    path('restupdate',views.restupdate,name='restupdate'),
    path('newitem',views.newitem,name='newitem'),
    path('mycart',views.mycart,name='mycart'),
    path('makecart',views.makecart,name='makecart'),
    path('restorders',views.restorder,name='restorder'),
    path('orderconfirm/<state>/<orderid>',views.orderconfirm,name='orderconfirm'),
    path('locaterestaurants/<location>', views.locaterestaurants, name='locaterestaurants'),
    path('showrestaurant/<restaurant>', views.showrestaurant, name='showrestaurant'),
    path('makeorderconfirm', views.makeorderconfirm, name='makeorderconfirm'),
    path('makeprev', views.makeprev, name='makeprev'),
    path('feedback', views.feedback, name='feedback'),
    path('feedbackthanks', views.feedbackthanks, name='feedbackthanks'),
    path('hotel/apiview/',views.HotelAPIView.as_view()),
    path('menu/apiview/',views.MenuAPIView.as_view()),
    path('customer/apiview/',views.CustomerOrdersAPIView.as_view()),
]

Foodezz/payments/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from Hotel import models as Hotelmodels
#from gpstrack.models import Driver

class Orders(models.Model):
    orderid = models.CharField(max_length=12)
    customerid=models.ForeignKey(User, on_delete=models.PROTECT)
    restaurantid=models.ForeignKey(Hotelmodels.RestaurantLog, on_delete=models.PROTECT)
    deliveryid=models.CharField(max_length=12)

    #driverid = models.ForeignKey(Driver, on_delete=models.PROTECT)

    foodname=models.CharField(max_length=150)
    quantity=models.CharField(max_length=4)
    price=models.CharField(max_length=5)
    date=models.DateTimeField(default=datetime.now, blank=True)
    status=models.CharField(max_length=150)

    def __str__(self):
        return self.foodname + ' ' + self.orderid

class CustomerCart(models.Model):
    customerid=models.ForeignKey(User, on_delete=models.PROTECT)
    restaurantid = models.ForeignKey(Hotelmodels.RestaurantLog, on_delete=models.PROTECT)
    foodname=models.CharField(max_length=150)
    status=models.CharField(max_length=50,default='buylater')

    def __str__(self):
        return self.customerid

class Feedback(models.Model):
    rate=models.IntegerField()
    suggestion=models.CharField(max_length=200)

Foodezz/payments/views.py
from payments.models import Orders, CustomerCart, Feedback
from Hotel.models import RestaurantLog, RestaurantItems
from Users.models import User_Profile as CustomerLog
from django.shortcuts import render,redirect
from django.http import HttpResponse
from gpstrack import views as gps
from django.contrib.auth.decorators import login_required
from Paypal import views
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings
from django.template.loader import render_to_string
from rest_framework import generics
from .serializer import HotelSerializer,MenuSerializer,CustomerSerializer


def search(request):
    var=request.POST['myCountry']
    place=RestaurantLog.objects.values_list('city').distinct()
    rest=RestaurantLog.objects.values_list('name').distinct()
    print(var)
    for i in rest:
        for j in i:
            if (var==j):
                rest_id = RestaurantLog.objects.get(name=var)
                data1 = RestaurantItems.objects.filter(restaurantid=rest_id)
                restaurant = RestaurantLog.objects.all()

                data = {'food': data1, 'rest': var}
                return render(request, 'payments/foodselection.html', data)
    for i in place:
        for j in i:
            if (var==j):
                return locaterestaurants(request, var)


#needed
def makelocations(request):
    location=RestaurantLog.objects.values('city').distinct()
    data={'locations':location}
    return render(request, 'payments/showlocations.html', data)

#needed
def locaterestaurants(request, location):
    #location=request.POST['submit']
    restaurant=RestaurantLog.objects.filter(city=location)
    data={'restaurants':restaurant}
    return render(request, 'payments/locaterestaurants.html', data)

#needed
def showrestaurant(request, restaurant):
    # restaurant=request.POST['submit']
    rest=RestaurantLog.objects.filter(name=restaurant)
    rest_id="1"
    for i in rest:
        rest_id=i.id
    data1=RestaurantItems.objects.filter(restaurantid=rest_id)
    data={'food':data1, 'rest':restaurant}
    return render(request, 'payments/foodselection.html', data)

#needed
@login_required
def pay(request,rest):
    quantity=request.POST['quantity']
    buyoradd=request.POST['button']
    rest_id = RestaurantLog.objects.get(name=rest)

    foodname = request.POST['food']
    # customerid = request.session['customer_id']
    # customer_id = CustomerLog.objects.get(pk=customerid)
    customer_id = request.user

    if(buyoradd=='add to cart'):
        if not CustomerCart.objects.filter(customerid=customer_id, restaurantid=rest_id, foodname=foodname):
            CustomerCart.objects.create(customerid=customer_id, restaurantid=rest_id, foodname=foodname)
        data1 = RestaurantItems.objects.filter(restaurantid=rest_id)
        data = {'food': data1, 'rest': rest}
        return render(request, 'payments/foodselection.html', data)

    else:
        order_id='0'
        if Orders.objects.all():
            orders=Orders.objects.all()
            for i in orders:
                order_id=i.orderid
        orderid=int(order_id)+1
        order_id=str(orderid)
        price=int(RestaurantItems.objects.get(restaurantid=rest_id, foodname=foodname).price)*int(quantity)
        Orders.objects.create(orderid=order_id,customerid=customer_id,restaurantid=rest_id,foodname=foodname,quantity=quantity,price=price,status='SentToRestaurant')

        data1 = RestaurantItems.objects.filter(restaurantid=rest_id)
        restaurant=rest_id.name
        data = {'food': data1, 'rest': restaurant}
        return views.payment_button(request, foodname, quantity, price, orderid)

#needed
@login_required
def mycart(request):
    state=request.POST['button']
    food = request.POST['food_id']


    if(state=='buynow'):

        q=food+'_quantity'
        print(q)
        quantity = request.POST[str(q)]
        food=CustomerCart.objects.filter(pk=food)
        for i in food:
            foodname=i.foodname
            rest_id=i.restaurantid
        customer_id = request.user

        order_id = '0'
        if Orders.objects.all():
            orders = Orders.objects.all()
            for i in orders:
                order_id = i.orderid
        orderid = int(order_id) + 1
        order_id = str(orderid)

        print(foodname, rest_id, quantity)
        price = int(RestaurantItems.objects.get(restaurantid=rest_id, foodname=foodname).price) * int(quantity)
        Orders.objects.create(orderid=order_id, customerid=customer_id, restaurantid=rest_id, foodname=foodname,
                              quantity=quantity, price=price, status='SentToRestaurant')

        return views.payment_button(request, foodname, quantity, price, orderid)

    elif(state=='remove from cart'):
        CustomerCart.objects.filter(pk=food).delete()

    return makecart(request)

#needed
@login_required
def makecart(request):
    if request.user.is_authenticated:
        later = CustomerCart.objects.filter(customerid=request.user.id)
        restdata = RestaurantLog.objects.all()
        food=RestaurantItems.objects.all()
        data = {'later': later, 'rest': restdata, 'food':food}
        return render(request, 'payments/mycart.html', data)


#needed
@login_required
def makeorderconfirm(request):
    # cust_id=CustomerLog.objects.get(pk=request.session['customer_id'])
    if request.user.is_authenticated:
        cust_id=request.user.id
        order=Orders.objects.filter(customerid=cust_id,status__in=['SentToRestaurant','OutForDelivery'])
        restdata=RestaurantLog.objects.all()
        data = {'orders':order, 'rest':restdata}
        return render(request, 'payments/orderconfirmation.html', data)

#needed
@login_required
def orderconfirm(request,state,orderid):
    if state=='track':
        driver=Orders.objects.get(orderid=orderid)
        return gps.map(request, driver.deliveryid)
    else:
        Orders.objects.filter(orderid=orderid).update(status='success')
        #feedback
        subject='Feedback'
        message=render_to_string('payments/email.html')
        email_from=settings.EMAIL_HOST_USER
        recipient_list=['santosh.p17@iiits.in']
        send_mail(subject, message, email_from, recipient_list)

        return makeorderconfirm(request)

def feedback(request):
    return render(request, 'payments/feedback.html')

def feedbackthanks(request):
    rate=request.POST['rate']
    suggestion=request.POST['suggestion']
    print(rate,suggestion)
    Feedback.objects.create(rate=rate, suggestion=suggestion)
    return render(request, 'payments/feedbackthanks.html')

@login_required
def makeprev(request):
    cust_id=request.user.id
    order=Orders.objects.filter(customerid=cust_id, status='success')
    restdata = RestaurantLog.objects.all()
    data={'order':order, 'rest':restdata}
    return render(request, 'payments/previousbookings.html', data)


####################################################################################################################
#Restaurant


#needed
def restupdate(request):
    submit = request.POST['submit']

    if(submit=='Update'):
        rest_id = request.session['rest_id']
        data1 = RestaurantItems.objects.filter(restaurantid=rest_id)
        for i in data1:
            foodname=i.foodname
            price=request.POST[foodname+'_price']
            availability=request.POST[foodname+'_availability']
            RestaurantItems.objects.filter(restaurantid=rest_id, foodname=foodname).update(price=price,availability=availability)
        return makerestupdate(request)

    elif(submit=='Add New Item'):
        restaurant = request.session['rest_name']
        data = {'rest': restaurant}
        return render(request,'payments/newitem.html',data)

    else:
        foodname=request.POST['foodname']
        rest_id = request.session['rest_id']
        RestaurantItems.objects.filter(restaurantid=rest_id, foodname=foodname).delete()
        return makerestupdate(request)

#needed
def newitem(request):
    restid=request.session['rest_id']
    rest_id=RestaurantLog.objects.get(pk=restid)
    foodname=request.POST['foodname']
    type=request.POST['type']
    category=request.POST['category']
    price=request.POST['price']
    availability=request.POST['availability']
    foodimage=request.FILES['foodimage']
    if RestaurantItems.objects.filter(foodname=foodname):
        return HttpResponse('Same foodname exists try creating with other food name.')
    else:
        RestaurantItems.objects.create(restaurantid=rest_id,foodname=foodname,type=type,category=category,price=price,availability=availability,foodimage=foodimage)
        data1 = RestaurantItems.objects.filter(restaurantid=rest_id)
        restaurant = request.session['rest_name']
        data = {'food': data1, 'rest': restaurant}
        return render(request, 'payments/restaurantupdate.html', data)

#needed
def makerestupdate(request):
    data1 = RestaurantItems.objects.filter(restaurantid=request.session['rest_id'])
    order = Orders.objects.filter(restaurantid=request.session['rest_id'], status='SentToRestaurant')
    inprogress = Orders.objects.filter(restaurantid=request.session['rest_id'], status='OutForDelivery')
    data = {"food": data1, "rest": request.session['rest_name'], "orders": order, "inpro":inprogress}
    return render(request, 'payments/restaurantupdate.html', data)

#needed
def restorder(request):
    Orders.objects.filter(orderid=request.POST['orderid']).update(deliveryid=request.POST['deliveryid'], status='OutForDelivery')
    return makerestupdate(request)

class HotelAPIView(generics.ListAPIView):
    serializer_class=HotelSerializer
    def get_queryset(self):
        qs = RestaurantLog.objects.all()
        query = self.request.GET.get("q")
        if query is not None:
            qs = qs.filter(city=query)
        return qs

class MenuAPIView(generics.ListAPIView):

Foodezz/payments/templates/payments/buynow.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>buynow</title>
</head>

<body>
     <form method="POST" action="{% url 'payments:pay' %}">
         {% csrf_token %}
         {% for foodname in food %}
             <input type="text" name='foodname' value="{{ foodname.foodname }}">
             {% for i in rest%}
                 {% if i == foodname.restaurantid %}
                     <input type="text" name="restname" value="{{ i.name }}">
                 {% endif %}
             {% endfor %}
             <input type="number" name="quantity" min="1" max="5"><br>
         {% endfor %}
         <input type="submit" value="buy now">
     </form>
</body>
</html>

Foodezz/payments/templates/payments/email.html
Hi,
Please click on the link to send feedback for your order
 http://127.0.0.1:8000{% url 'payments:feedback' %} 

Foodezz/payments/templates/payments/feedback.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
	<title>Feedback</title>
	<style>
		#submit:hover{color:#BB04BB}
		#submit{margin-left:45%;background:transparent;border:2px solid;width:80px;height:30px;font-size:20px;border-radius:5px}
	</style>
</head>

<body style="background-image:url({% static "images/back3.jpg" %});position:absolute">
	<div style="width:400%;height:500px;margin:20% 20% 30% 20%;position:relative">
	<form action="{% url "payments:feedbackthanks" %}" style="margin-left:30%;margin-top:0%" method="POST">
        {% csrf_token %}
		<span style="font-size:40px">FEEDBACK FORM</span>
		<h2>Please rate us (out of 10)<sup>*</sup>:</h2>
		<input type="number" name="rate" id="rate" style="border-radius:10px;background:transparent;border:2px solid;" min="1" max="10" value="1" required autofocus><br>
		<h2>Any valuable suggestion:</h2><br>
		<textarea id="suggestion" name="suggestion" style="width:50%;height:150px;background:transparent;font-size:20px;border:2px solid;border-radius:10px" maxlength="200">
		</textarea><br>
		<button type="submit" style="" id="submit" onclick="validate()">Submit</button>
	</form>
	</div>

<script>
	function validate() {
		var x=document.getElementById('rate').value;
		if(isNaN(x) || x<1 || x>10) {
			alert("Please give rating in range 1 to 10");
		}
	}
</script>
</body>
</html>

Foodezz/payments/templates/payments/feedbackthanks.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
	<title>Feedback</title>
	<style>
		#submit:hover{color:#BB04BB}
		#submit{margin-left:45%;background:transparent;border:2px solid;width:80px;height:30px;font-size:20px;border-radius:5px}
	</style>
</head>

<body style="background-image:url({% static "images/back3.jpg" %});position:absolute">
	<div style="width:400%;height:500px;margin:20% 20% 30% 20%;position:relative">
        Thanks for your valuable feedback
    </div>
</body>
</html>

Foodezz/payments/templates/payments/foodselection.html
{% extends 'Users/Base.html' %}
{% load widget_tweaks %}

{% load staticfiles %}
{% block head %}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Satisfy|Bree+Serif|Candal|PT+Sans">
  <link href='https://fonts.googleapis.com/css?family=Amarante' rel='stylesheet'>
  <link href='https://fonts.googleapis.com/css?family=Allura' rel='stylesheet'>
  <link href='https://fonts.googleapis.com/css?family=Alegreya SC' rel='stylesheet'>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" type="text/css" href="{%static  "css/foodselection.css"%}">
  <title>Hotel Details</title>

{% endblock head %}

{% block body %}

<script>
        function foodname(food_name) {
            document.getElementById('food_name').value=food_name
            food=food_name.concat("_quantity")
            document.getElementById('quantity').value=document.getElementById(food).value
        }
</script>
{##}
{#  <!--banner-->#}
{#  <div class="nav" style="height:100px;z-index: 1;background-color: black;position: fixed;top: 0;left:0;width:100%">#}
{#      <h1 class="logo">Food33z</h1>#}
{#	  <span style="height:100%;width:100px;margin-top:30px;margin-left:40%;float:left"><a class="logout" style="" href="" target="_blank"><i class="fa fa-home"></i>  Home</a></span>#}
{#	  <span style="height:100%;width:120px;margin-top:30px;margin-left:2%;float:left"><a class="logout" style="" href="" target="_blank"><i class="fa fa-cart-plus"></i>  My Cart</a></span>#}
{#	  <span style="height:100%;width:100px;margin-top:30px;margin-left:2%;float:left"><a class="logout" style="" href="#menu-list"><i class="fa fa-bars"></i>  Menu </a></span>#}
{#	  <span style="height:100%;width:120px;margin-top:30px;margin-left:2%;float:left"><a class="logout" style="margin-left:5%;width:200px;margin-top:60px;" href="#contact"><i class="fa fa-phone"></i>  Contact </a></span>#}
{#      <span style="height:100%;width:120px;margin-top:30px;margin-left:2%;float:left"><a class="logout" style="" href=""><i class="fa fa-power-off"></i>  Log Out </a></span>#}
{#	</div>#}
  <section id="banner" style="background: url({%static "images/banner-bg.jpg"%}) no-repeat center top;background-size:cover">
    <div class="bg-color" style="border:1px solid black">


          <div style="text-align:center;">
            <h1 class="logo-name">{{ rest }}</h1>
            <h2>Food To fit your lifestyle & health.</h2>
            <p>Specialized in both North & South Indian Meals!!</p>
          </div>


    </div>
  </section>
  <!-- / banner -->

  <!-- menu -->
  <section id="menu-list" class="">
    <div>
	   <div class="food-menu" style="float:left;">
        <div>
          <h1 class="header-h" style="font-family:Alegreya SC">Menu List</h1>
        </div>

        <div id="menu-flters" style="margin-left: 10%">
          <ul>
            <li><a class="filter active"  data-filter=".menu-restaurant">Show All</a></li>
			<li><a class="filter"  data-filter=".soup">Soup</a></li>
			<li><a class="filter"  data-filter=".starter">Starter</a></li>
			<li><a class="filter"  data-filter=".main_course">Main Course</a></li>
			<li><a class="filter"  data-filter=".dessert">Desserts</a></li>
            <li><a class="filter"  data-filter=".beverage">Beverages</a></li>
          </ul>
        </div>

          <div style="float:left;font-family:Alegreya SC;width:100%;margin-bottom:60px;margin-left: 2%">
              <span  style="font-size:35px;margin-left:8%">Item Name</span>
			  <span  style="font-size:35px;margin-left:17%">Price</span>
              <span  style="font-size:35px;margin-left:9%">Quantity</span>
          </div>

    <form method="POST" action="{% url 'payments:pay' rest %}">
        {% csrf_token %}
        {% for fooddata in food %}
            <div class="{{ fooddata.category }} menu-restaurant" style="float:left;width:45%;height:132px;margin-left: 4%">
            <span class="clearfix" style="width:600px">
              <span style="left: 166px; right: 44px;" class="menu-line"></span>
              <span class="menu-price" style="color:#000">₹{{ fooddata.price }}</span>
            </span>
            <img src="{{ fooddata.foodimage.url }}" alt="image not available" style="width:100px;height:100px;border-radius:50%;border:2px solid" class="menu-title">
            <span class="menu-title" style="color:#000000">{{ fooddata.foodname }}</span>
          </div>
		  <div class="{{ fooddata.category }} menu-restaurant" style="width:35%;margin-right:12%;height:132px;">
				<input type="number" name="quantity" id="{{ fooddata.foodname }}_quantity" value="1" min="1" max="10" style="text-align:center;margin-left: 7%;border-radius:5px;border:1px solid green;width:100px;height: 30px">
                <input type="submit" class="btns" id="{{ fooddata.foodname }}" name="button" value="add to cart" onclick="foodname(this.id)" style="font-size: 25px;border-radius: 10px;border:2px solid #FFB03B;font-family:Alegreya SC">
                <input type="submit" class="btns" id="{{ fooddata.foodname }}" name="button" value="buynow" onclick="foodname(this.id)" style="font-size: 25px;border-radius: 10px;margin-right: 20px;border:2px solid #FFB03B;font-family:Alegreya SC">
		  </div>
        {% endfor %}
    <input id="food_name" name="food" type="text" hidden>
    <input id="quantity" name="quantity" type="number" value="1" hidden>
    </form>


		  
		  
	  </div>
    </div>
  </section>
{#  <section class="section-padding" id="contact" style="height:200px;width:100%;background-color:black;position:relative;bottom:0;left:0">#}
{#		<div class="row">#}
{#			<div style="padding-left:35%;width:300px;">#}
{#				<h1>Swathi</h1>#}
{#				<address>Tada,Chittoor<br>Andhra Pradesh<br>#}
{#				Contact No:64687456748<br>#}
{#				Email:tsfsugya@hjg#}
{#				</address><br>#}
{#			</div>#}
{#			<div style="margin-right:5%;">#}
{#				<a href="https://www.google.co.in/search?ei=Uyn8W6WbOsvXvgT7o7WwCw&q=swathi+hotel+tada&oq=swathi+ho+tada&gs_l=psy-ab.3.0.0i7i30.18836.22040..24864...0.0..1.411.2517.0j6j4j1j1......0....1..gws-wiz.......0j0i71j0i13j0i7i10i30j0i30j0i5i30.wTAPD12vj_w" target="_blank" style="text-decoration:none;"><img src="google.png" alternate="google" class="icons" ></a>#}
{#				<a href="" target="_blank" style="text-decoration:none;"><img src="instagram.png" alternate="instagram" class="icons" ></a>#}
{#				<a href="" target="_blank" style="text-decoration:none;"><img src="facebook-icon.png" alternate="facebook" class="icons" ></a>				#}
{#			</div>#}
{#		</div>#}
{#  </section>#}

  <script src="https://code.jquery.com/jquery-2.1.1.js"></script>

  <script src="{% static "js/hotels.js"%}"></script>
{% endblock body %}

Foodezz/payments/templates/payments/locaterestaurants.html
<!DOCTYPE html>
{% extends 'Users/Base.html' %}
{% load widget_tweaks %}

{% load staticfiles %}
{% block head %}

    <meta charset="utf-8">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge">
  	<meta name="viewport" content="width=device-width, initial-scale=1">
  	<meta name="keywords" content="footer, contact, form, icons" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


  	<link rel="stylesheet" href="css/demo.css">
  	<link rel="stylesheet" href="css/footer-distributed-with-contact-form.css">

  	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">

  	<link href="http://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">
    <title>Welcome to Food3zz</title>
    <link rel="stylesheet" href="{% static "css/locaterestaurants.css" %}" alt="oh crap">
    <script src="{% static "JS/ase1.js" %}"></script>

{% endblock head %}
{% block body %}

{#<div>#}
{#<ul class="nav">#}
{#    <li id="settings">#}
{#        <a href="#"><img src=" {% static "images/123.png" %}" height=100px width=220px/></a>#}
{#    </li>#}
{#    <li>#}
{#        <a href="#">About Us</a>#}
{#    </li>#}
{#    <li id="search">#}
{#        <form action="" method="get">#}
{#            <input type="text" name="search_text" id="search_text" placeholder="Search"/>#}
{#            <input type="button" name="search_button" id="search_button"></a>#}
{#        </form>#}
{#    </li>#}
{#    <li id="options">#}
{#        <a href="#">Hi</a>#}
{#        <ul class="subnav">#}
{#            <li><a href="#">My Cart</a></li>#}
{#            <li><a href="#">Profile</a></li>#}
{#            <li><a href="#">Logout</a></li>#}
{#        </ul>#}
{#    </li>#}
{#</ul>#}

<script src="prefixfree-1.0.7.js" type="text/javascript"></script>

    <div class="row">
    {% for restaurant in restaurants %}
        <div class="col-sm-4">
            <div class="card" style="width: 18rem;margin-top:100px">
                <img class="card-img-top" src="{{ restaurant.restimage.url }}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">{{ restaurant.name }}</h5>
                        <p class="card-text">Address:{{ restaurant.address }}, {{ restaurant.street }}, {{ restaurant.city }},{{ i }}</p>
                        <a href="{% url 'payments:showrestaurant' restaurant.name %}">Check it out!</a>
                    </div>
                </div>
        </div>
    {% endfor %}
    </div>


</div>

{% endblock body %}

Foodezz/payments/templates/payments/newitem.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>new item</title>
</head>
<body>
     <form method="POST" action="{% url 'payments:newitem' %}" enctype="multipart/form-data">
         {% csrf_token %}
         <input type="text" name="restaurantname" value="{{ rest }}" readonly><br>
         food name:<input type="text" name="foodname"><br>
         type:<select name="type">
             <option value="veg">veg</option>
             <option value="non-veg">non-veg</option>
         </select><br>
         category:<select name="category">
            <option value="starter">starter</option>
            <option value="soup">soup</option>
            <option value="main_course">main course</option>
            <option value="dessert">dessert</option>
            <option value="beverages">beverages</option>
         </select><br>
         price:<input type="number" name="price"><br>
         avaialability<input type="number" name="availability"><br>
         image<input type="file" name="foodimage" accept="image/*"><br>
         <input type="submit" value="create">
     </form>
</body>
</html>

Foodezz/payments/templates/payments/payment.html
...
<h1>Show me the money!</h1>
<!-- writes out the form tag automatically -->
{{ form.render }}

Foodezz/payments/templates/payments/showlocations.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>locations</title>
</head>
<body>
    <form method="POST" action="{% url 'payments:locaterestaurants' %}">
         {% csrf_token %}
        {% for location in locations %}
            <input type="submit" name="submit" value="{{ location.city }}"><br>
        {% endfor %}
    </form>
</body>
</html>